name: JOSHUA DOUGLAS-BAGLEY / GRAPHIC DESIGNER
favicon: null
layout_spectrum: 0.51287
typography_spectrum: 0.09986
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#0e212b'
    - '#324a52'
    - '#547f91'
    - '#66a5c7'
  brandStrength: 0.45916994265280664
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
