layout_spectrum: 0.51287
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4038786
  brandStrength: 0.4591699426528066
  lightness: 0.4755481
  brandColors:
    - '#020202'
    - '#0e212b'
    - '#324a52'
    - '#547f91'
    - '#66a5c7'
  rhythmicContrast: 0
typography_spectrum: 0.6610456
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: JOSHUA DOUGLAS-BAGLEY / GRAPHIC DESIGNER
