name: JOSHUA DOUGLAS-BAGLEY / GRAPHIC DESIGNER
favicon: null
layout_spectrum: 0.6502833156846464
typography_spectrum: 0.4546354461926967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.45916994265280664
  lightness: 0.49413968133740127
  saturation: 0.28084998950362206
  rhythmicContrast: 0.8907920070923865
purpose: []
